name: Robotics Club
title: Robotics Club
url: https://students.iitk.ac.in/roboclub
paginate: 5
paginate_path: "/blog/page:num/"
plugins: 
- jekyll-paginate

markdown: kramdown

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false

highlighter: rouge

exclude: ["/docs"]
destination: "/home/shashi/gitrepo/robotics_club/docs/"
